apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mercure.fullname" . }}
  labels:
    {{- include "mercure.labels" . | nindent 4 }}
type: Opaque
stringData:
  publisher-jwt-key: {{ .Values.publisherJwtKey | default (randAlphaNum 40) }}
  subscriber-jwt-key: {{ .Values.subscriberJwtKey | default (randAlphaNum 40) }}
data:
  transport-url: {{ .Values.transportUrl | b64enc | quote }}
  extra-directives: {{ .Values.extraDirectives | b64enc | quote }}
  license: {{ .Values.license | b64enc | quote }}
  caddy-extra-directives: {{ .Values.caddyExtraDirectives | b64enc | quote }}
